# &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;Assignment

## &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&nbsp;&nbsp;&nbsp;Web Scraping

The libraries which are to be used in the sheet are imported below:

In [1]:
import  requests
from  bs4 import BeautifulSoup
import pandas as pd
import qgrid
import re

<div class="alert alert-block alert-info">
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<b>Function to input the url as text and return the response :</b></div>

### Write a python program to display all the header tags from

In [2]:
def get_url(text):
    url = requests.get(text)
    return (url)

In [3]:
def get_soup(txt):
    soup = BeautifulSoup(get_url(txt).text, 'lxml')
    return soup

<div class="alert alert-block alert-info">
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<b>Function to return headers for the given URL: </b></div>

In [4]:
def get_header(url): 
    soup = BeautifulSoup(url.text, 'html.parser')
    story = soup.find_all(['h1', 'h2','h3'])
    for i in story:
        print(i.text)

<div class="alert alert-block alert-success">
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;Providing the function with the url: <b><a>https://en.wikipedia.org/</a></b> to get headers: 
</div>

Question 1

In [5]:
get_header(get_url('https://en.wikipedia.org/wiki/Main_Page'))

Main Page
Welcome to Wikipedia
From today's featured article
Did you know ...
In the news
On this day
Today's featured picture
Other areas of Wikipedia
Wikipedia's sister projects
Wikipedia languages
Navigation menu

Search

<div class="alert alert-block alert-success">
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<b>Task Successful</b> 
</div>

### Write a python program to display IMDB’s Top rated 100 movie's data (i.e.name,rating,year of release) and make data frame.

In [6]:
#url = 'http://www.imdb.com/chart/top'
def get_soup(txt):
    soup = BeautifulSoup(get_url(txt).text, 'lxml')
    return soup

In [7]:
def make_data_list(soup):
    movies = soup.select('td.titleColumn')
    links = [a.attrs.get('href') for a in soup.select('td.titleColumn a')]
    crew = [a.attrs.get('title') for a in soup.select('td.titleColumn a')]
    ratings = [b.attrs.get('data-value') for b in soup.select('td.posterColumn span[name=ir]')]
    votes = [b.attrs.get('data-value') for b in soup.select('td.ratingColumn strong')]

    lis = []
 
    for index in range(0, len(movies)):  
    # Separating  movie into: 'place',
    # 'title', 'year'
        movie_string = movies[index].get_text()
        movie = (' '.join(movie_string.split()).replace('.', ''))
        movie_title = movie[len(str(index))+1:-7]
        year = re.search('\((.*?)\)', movie_string).group(1)
        place = movie[:len(str(index))-(len(movie))]
     
        data = {"Name": movie_title,
            "Year of Release": year,
            "Rating": ratings[index],}
        lis.append(data)
    return lis

In [10]:
def make_display(lis):
    df = pd.DataFrame(lis)
    return df

In [11]:
make_display(make_data_list(get_soup("http://www.imdb.com/chart/top"))) #SOLUTION

                         Name Year of Release             Rating
0    The Shawshank Redemption            1994  9.240115425679013
1               The Godfather            1972  9.161217622110593
2             The Dark Knight            2008  8.994429811898343
3      The Godfather: Part II            1974   8.99027131799727
4                12 Angry Men            1957  8.950904511710823
..                        ...             ...                ...
245      Beauty and the Beast            1991  8.016418255400135
246                    Gandhi            1982   8.01506387690314
247                  The Help            2011  8.014288887397628
248                 Ah-ga-ssi            2016  8.012841847065145
249        Dances with Wolves            1990  8.008476392424567

[250 rows x 3 columns]

<div class="alert alert-block alert-success">
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<b>Task Successful</b> 
</div>

Question 3

In [12]:
def get_table(soup):
    return soup.find('table')

In [13]:
def get_rows(table):
    return table.find_all('tr')

In [14]:
def return_rating_movies(row):
    lis = []
    temp = row.text.strip().split('\n')
    for n in range(0,len(temp)):
        if temp[n] != '':
            lis.append(temp[n])
    return [lis[1].strip(),lis[2],lis[3]]

In [15]:
def make_rating_table(url):
    final_list = []
    table = get_table(get_soup(url))
    rows = get_rows(table)
    for i in range(1,11):
        final_list.append(return_rating_movies(rows[i]))
    
    df = pd.DataFrame(final_list)
    df.rename(columns = {0:'Title', 1:'Year of release',2:'Rating'}, inplace = True)
    return df

In [16]:
(make_rating_table('https://www.imdb.com/india/top-rated-indian-movies/'))

               Title Year of release Rating
0           Jai Bhim          (2021)    8.4
1         Anbe Sivam          (2003)    8.4
2  Pariyerum Perumal          (2018)    8.4
3            Golmaal          (1979)    8.4
4            Nayakan          (1987)    8.4
5           3 Idiots          (2009)    8.4
6        Apur Sansar          (1959)    8.4
7    Soorarai Pottru          (2020)    8.4
8  C/o Kancharapalem          (2018)    8.3
9  Kumbalangi Nights          (2019)    8.3

Question 4

In [17]:
def get_card(soup):
    return soup.find_all('div', class_ = 'Card__BaseCard-sc-b3n78k-0 lfjhF NewProductCard__CardStyled-sc-j0e7tu-0 hzPSVW NewProductCard__CardStyled-sc-j0e7tu-0 hzPSVW')

In [18]:
def get_subcard(card):
    return card.find('div',class_ = 'Card__BaseCard-sc-b3n78k-0 cXRroa NewProductCard__DetailCard_Desktop-sc-j0e7tu-2 eEBPAI NewProductCard__DetailCard_Desktop-sc-j0e7tu-2 eEBPAI')

In [19]:
def get_product_name(subcard):
    return subcard.find('p', class_ = 'Text__StyledText-sc-oo0kvp-0 cPgaBh NewProductCard__ProductTitle_Desktop-sc-j0e7tu-4 hofZGw NewProductCard__ProductTitle_Desktop-sc-j0e7tu-4 hofZGw').text

In [20]:
def get_discounted_price(subcard):
    return subcard.find('h5').text

In [21]:
def get_discount_percentage(subcard):
    return subcard.find('span', color = 'greenBase').text

In [22]:
def make_product_list(subcard):
    return [get_product_name(subcard), get_discounted_price(subcard), get_discount_percentage(subcard)]

In [23]:
def make_product_table(url):
    product_list = []
    soup = get_soup(url)
    card = get_card(soup)
    
    for i in range(0,len(card)):
        subcard = get_subcard(card[i])
        product_list.append(make_product_list(subcard))
    df = pd.DataFrame(product_list)
    df.rename(columns = {0:'Product Name', 1:'Discounted Price',2:'Discount Rate'}, inplace = True)
    
    return df

In [24]:
make_product_table('https://meesho.com/bags-ladies/pl/p7vbp')

                            Product Name Discounted Price Discount Rate
0           Trendy Stylish Women Handbag             ₹364       12% off
1    Graceful Fashionable Women Handbags             ₹570        8% off
2      Classic Attractive Women Handbags             ₹534        9% off
3        Voguish Alluring Women Handbags             ₹242       15% off
4     Classic Fashionable Women Handbags             ₹940        5% off
5       FashionableLatest Women  handbag              ₹85       15% off
6             Fancy Modern Women Handbag            ₹1392        3% off
7       Elite Fashionable Women Handbags            ₹1349        4% off
8       Graceful Alluring Women Handbags             ₹434       10% off
9    New Collections Of Garbage Handbags             ₹734        6% off
10      Classic Versatile Women Handbags             ₹660        7% off
11                              Handbags            ₹8949        1% off
12    Graceful Attractive Women Handbags             ₹450       10% off
13        Graceful Women Women Handbags              ₹284       15% off
14          Styles Latest Women handbags            ₹1119        4% off
15                   Attractive Handbags             ₹481        9% off
16             Fashionable Women Handbag             ₹304       14% off
17      Classic Versatile Women Handbags             ₹749        6% off
18      Classic Versatile Women Handbags             ₹267       15% off
19       Ravishing Classy Women Handbags             ₹566        8% off

Question 5

Part 1

In [25]:
def get_Team_ODI_List(soup):
    results = soup.find_all("td")
    lis = []
    for i in range(1,len(results),5):
        if i == len(results)-1:
            break
        else: 
            name = results[i].text.strip().split(".")[-1].strip().split("\n")[0]
            matches = results[i+1].text#strip().split(".")[-1].strip().split("\n")[-1][1:-1]
            points = results[i+2].text
            rating = results[i+3].text.strip()
        lis.append([name ,matches ,points ,rating])
    return lis

In [26]:
def display_Df(url):
    df = pd.DataFrame(get_Team_ODI_List(get_soup(url)))
    df.rename(columns = {0:'Team', 1:'Matches',2:'Points', 3:'Rating'}, inplace = True)
    print(df)
    return "Task Successful"

In [27]:
display_Df("https://www.icc-cricket.com/rankings/mens/team-rankings/odi")

                Team Matches Points Rating
0        New Zealand      19  2,316    122
1            England      32  3,793    119
2          Australia      31  3,475    112
3              India      38  4,162    110
4       South Africa      31  3,167    102
5           Pakistan      30  2,921     97
6         Bangladesh      36  3,350     93
7          Sri Lanka      35  2,835     81
8        West Indies      36  2,788     77
9        Afghanistan      23  1,562     68
10           Ireland      28  1,445     52
11          Scotland      10    452     45
12          Zimbabwe      23    951     41
13       Netherlands      12    433     36
14               UAE      20    651     33
15              Oman      24    720     30
16           Namibia      13    268     21
17             Nepal      17    308     18
18     United States      14    232     17
19  Papua New Guinea      19    207     11

'Task Successful'

Part 2

In [28]:
#soup = get_soup('https://www.icc-cricket.com/rankings/mens/player-rankings/odi/batting')
def get_ODI_Batsmen(soup):
    results = soup.find_all("td")
    lis = []
    for i in range(0,len(results),5): 
        if i > 46:
            break
        else: 
            Player = results[i+1].text.strip()#Player NAME
            Team = results[i+2].text.strip() #Team
            Rating = results[i+3].text.strip() #Rating
        
        lis.append([Player, Team, Rating])
    return lis

In [29]:
def display_Batsmen_Ranking(url):
    df = pd.DataFrame(get_ODI_Batsmen(get_soup(url)))
    df.rename(columns = {0:'Player Name', 1:'Team',2:'Rating'}, inplace = True)
    print(df)
    return "Task Successful"

In [30]:
display_Batsmen_Ranking('https://www.icc-cricket.com/rankings/mens/player-rankings/odi/batting')

             Player Name Team Rating
0             Babar Azam  PAK    872
1            Virat Kohli  IND    811
2            Ross Taylor   NZ    794
3           Rohit Sharma  IND    791
4        Quinton de Kock   SA    789
5         Jonny Bairstow  ENG    775
6            Aaron Finch  AUS    771
7  Rassie van der Dussen   SA    769
8           David Warner  AUS    758
9            Imam-ul-Haq  PAK    746

'Task Successful'

Part 3

In [31]:
def get_ODI_bowlers(soup):
    results = soup.find_all("td")
    lis = []
    for i in range(0,len(results),5): 
        if i > 46:
            break
        else: 
            Player = results[i+1].text.strip()#Player NAME
            Team = results[i+2].text.strip() #Team
            Rating = results[i+3].text.strip() #Rating
        lis.append([Player, Team, Rating])
    return lis

In [37]:
def display_Bowlers_ODI_Ranking(url):
    df = pd.DataFrame((get_ODI_bowlers(get_soup(url))))
    df.rename(columns = {0:'Player Name', 1:'Team',2:'Rating'}, inplace = True)
    print(df)
    return "Task Successful"

In [38]:
display_Bowlers_ODI_Ranking('https://www.icc-cricket.com/rankings/mens/player-rankings/odi/bowling')

        Player Name Team Rating
0       Trent Boult   NZ    733
1    Josh Hazlewood  AUS    705
2      Chris Woakes  ENG    700
3        Matt Henry   NZ    687
4  Mujeeb Ur Rahman  AFG    681
5    Jasprit Bumrah  IND    679
6      Mehedi Hasan  BAN    661
7   Shakib Al Hasan  BAN    657
8        Adam Zampa  AUS    650
9       Rashid Khan  AFG    650

'Task Successful'

Question 6

Part 1

In [39]:
def get_Team_ODI_Women(soup):
    results = soup.find_all("td")
    lis = []
    for i in range(1,len(results),5):
        if i == len(results)-1:
            break
        else: 
            name = results[i].text.strip().split(".")[-1].strip().split("\n")[0]
            matches = results[i+1].text#strip().split(".")[-1].strip().split("\n")[-1][1:-1]
            points = results[i+2].text
            rating = results[i+3].text.strip()
        lis.append([name ,matches ,points ,rating])
    return lis

In [40]:
def display_Df_W(url):
    df = pd.DataFrame(get_Team_ODI_Women(get_soup(url)))
    df.rename(columns = {0:'Team', 1:'Matches',2:'Points', 3:'Rating'}, inplace = True)
    print(df)
    return "Task Successful"

In [41]:
display_Df_W("https://www.icc-cricket.com/rankings/womens/team-rankings/odi")

            Team Matches Points Rating
0      Australia      29  4,840    167
1   South Africa      28  3,504    125
2        England      30  3,533    118
3          India      29  2,890    100
4    New Zealand      31  3,018     97
5    West Indies      28  2,478     89
6     Bangladesh      12    935     78
7       Pakistan      26  1,753     67
8        Ireland       5    240     48
9      Sri Lanka       5    233     47
10      Zimbabwe       8      0      0

'Task Successful'

Part 2

In [42]:
def get_ODI_Batsmen_W(soup):
    results = soup.find_all("td")
    lis = []
    for i in range(0,len(results),5): 
        if i > 46:
            break
        else: 
            Player = results[i+1].text.strip()#Player NAME
            Team = results[i+2].text.strip() #Team
            Rating = results[i+3].text.strip() #Rating
        
        lis.append([Player, Team, Rating])
    return lis

In [43]:
def display_Batsmen_Ranking_Women(url):
    df = pd.DataFrame(get_ODI_Batsmen_W(get_soup(url)))
    df.rename(columns = {0:'Player Name', 1:'Team',2:'Rating'}, inplace = True)
    print(df)
    return "Task Successful"

In [44]:
display_Batsmen_Ranking_Women('https://www.icc-cricket.com/rankings/womens/player-rankings/odi/batting')

         Player Name Team Rating
0    Laura Wolvaardt   SA    740
1        Beth Mooney  AUS    726
2        Meg Lanning  AUS    718
3     Natalie Sciver  ENG    705
4       Alyssa Healy  AUS    703
5        Mithali Raj  IND    686
6     Rachael Haynes  AUS    684
7     Tammy Beaumont  ENG    682
8  Amy Satterthwaite   NZ    681
9    Smriti Mandhana  IND    669

'Task Successful'

Part 3

In [45]:
def get_ODI_Women_All_Rounders(soup):
    results = soup.find_all("td")
    lis = []
    for i in range(0,len(results),5): 
        if i > 46:
            break
        else: 
            Player = results[i+1].text.strip()#Player NAME
            Team = results[i+2].text.strip() #Team
            Rating = results[i+3].text.strip() #Rating
            Career = results[i+4].text.strip() #Career best
        lis.append([Player, Team, Rating, Career])
    return lis

In [46]:
def display_Women_All_Rounders_Ranking(url):
    df = pd.DataFrame((get_ODI_Women_All_Rounders(get_soup(url))))
    df.rename(columns = {0:'Player Name', 1:'Team',2:'Rating',3: 'Career Best Rating'}, inplace = True)
    print(df)
    return "Task Successful"

In [47]:
display_Women_All_Rounders_Ranking('https://www.icc-cricket.com/rankings/womens/player-rankings/odi/all-rounder')

        Player Name Team Rating              Career Best Rating
0      Ellyse Perry  AUS    404   548 v West Indies, 11/09/2019
1    Natalie Sciver  ENG    376   391 v New Zealand, 16/09/2021
2    Marizanne Kapp   SA    359   419 v West Indies, 10/09/2021
3   Hayley Matthews   WI    340         365 v India, 12/03/2022
4       Amelia Kerr   NZ    335  339 v South Africa, 17/03/2022
5  Ashleigh Gardner  AUS    278    278 v Bangladesh, 25/03/2022
6     Deepti Sharma  IND    249  397 v South Africa, 09/10/2019
7     Jess Jonassen  AUS    246   308 v West Indies, 11/09/2019
8   Katherine Brunt  ENG    239     296 v Australia, 03/02/2022
9    Jhulan Goswami  IND    217     308 v Australia, 02/02/2016

'Task Successful'

<div class="alert alert-block alert-success">
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<b>Task Successful</b> 
</div>

Question 7

In [48]:
def get_headline(article):
    return article.h2.a.text

In [49]:
def get_date(article):
    return article.find('time', class_ = 'entry-time').text

In [50]:
def get_summary(article):
    return article.find('div',class_ = 'entry-content').text.strip()

In [51]:
def get_video_Code(article):
    yt = article.find('iframe',class_ = 'youtube-player')
    code = yt['src'].split('/')[4].split('?')[0]
    return code

In [52]:
def get_list(article):
    return [get_headline(article), get_date(article), get_summary(article), get_video_Code(article)]

In [53]:
def make_table(url):
    final_L = []
    soup = get_soup(url)
    articles = soup.find_all('article')
    for i in range(0,len(articles)):
        if i == 4:
            continue
        else:
            final_L.append(get_list(articles[i]))
    df = pd.DataFrame(final_L)
    df.rename(columns = {0:'Title', 1:'Date',2:'Summary',3: 'Youtube Code'}, inplace = True)
    
    return df

In [54]:
make_table('https://coreyms.com/')

,Title,Date,Summary,Youtube Code
0,Python Tutorial: Zip Files – Creating and Extr...,"November 19, 2019","In this video, we will be learning how to crea...",z0gguhEmWiY
1,Python Data Science Tutorial: Analyzing the 20...,"October 17, 2019","In this Python Programming video, we will be l...",_P7X8tMplsw
2,Python Multiprocessing Tutorial: Run Code in P...,"September 21, 2019","In this Python Programming video, we will be l...",fKl2JW_qrso
3,Python Threading Tutorial: Run Code Concurrent...,"September 12, 2019","In this Python Programming video, we will be l...",IEEhzQoKtQU
4,Python Quick Tip: The Difference Between “==” ...,"August 6, 2019","In this Python Programming Tutorial, we will b...",mO_dS3rXDIs
5,Python Tutorial: Calling External Commands Usi...,"July 24, 2019","In this Python Programming Tutorial, we will b...",2Fp1N6dof0Y
6,Visual Studio Code (Windows) – Setting up a Py...,"May 1, 2019","In this Python Programming Tutorial, we will b...",-nh9rCzPJ20
7,Visual Studio Code (Mac) – Setting up a Python...,"May 1, 2019","In this Python Programming Tutorial, we will b...",06I63_p-2A4
8,Clarifying the Issues with Mutable Default Arg...,"April 24, 2019","In this Python Programming Tutorial, we will b...",_JGmemuINww

Question 9

In [55]:
def get_name(tile):
    return tile.find('a',class_ = 'restnt-name ellipsis').text

In [56]:
def get_location(tile):
    return tile.find('div', class_ = 'restnt-loc ellipsis').text

In [57]:
def get_cuisines(tile):
    c = tile.find('div', class_ = 'detail-info')
    return (c.text.split("|")[1])

In [58]:
def get_rating(tile):
    return tile.find('div', class_= 'restnt-rating rating-4').text

In [59]:
def get_image_url(tile):
    return tile.find('img', class_= 'lazy-load-img no-img')['data-src']

In [60]:
def get_list_restnt(tile):
    return [get_name(tile), get_location(tile), get_cuisines(tile), get_rating(tile), get_image_url(tile)]

In [61]:
def make_restnt_table(url):
    final_L = []
    soup = get_soup(url)
    tiles = soup.find_all('div', class_ = 'restnt-main-wrap clearfix')
    for i in range(0,len(tiles)):
        final_L.append(get_list_restnt(tiles[i]))
    df = pd.DataFrame(final_L)
    df.rename(columns = {0:'Name', 1:'Location',2:'Cuisines',3: 'Rating', 4: 'Image URL'}, inplace = True)
    
    return df

In [62]:
make_restnt_table('https://www.dineout.co.in/delhi-restaurants/buffet-special')

,Name,Location,Cuisines,Rating,Image URL
0,Castle Barbeque,"Connaught Place, Central Delhi","North Indian, Chinese",3.5,https://im1.dineout.co.in/images/uploads/resta...
1,Jungle Jamboree,"3CS Mall,Lajpat Nagar - 3, South Delhi","North Indian, Asian, Italian",3.9,https://im1.dineout.co.in/images/uploads/resta...
2,Castle Barbeque,"Pacific Mall,Tagore Garden, West Delhi","Chinese, North Indian",3.9,https://im1.dineout.co.in/images/uploads/resta...
3,Cafe Knosh,"The Leela Ambience Convention Hotel,Shahdara, ...","Italian, Continental1 offer available",4.3,https://im1.dineout.co.in/images/uploads/resta...
4,The Barbeque Company,"Gardens Galleria,Sector 38A, Noida","North Indian, Chinese4 deals and 1 offer avai...",4,https://im1.dineout.co.in/images/uploads/resta...
5,India Grill,"Hilton Garden Inn,Saket, South Delhi","North Indian, Italian1 offer available",3.9,https://im1.dineout.co.in/images/uploads/resta...
6,Delhi Barbeque,"Taurus Sarovar Portico,Mahipalpur, South Delhi",North Indian,3.7,https://im1.dineout.co.in/images/uploads/resta...
7,The Monarch - Bar Be Que Village,"Indirapuram Habitat Centre,Indirapuram, Ghaziabad","North Indian, Chinese",3.9,https://im1.dineout.co.in/images/uploads/resta...
8,World Cafe,"Vibe by The Lalit Traveller,Sector 35, Faridabad","North Indian, Chinese, Continental1 offer ava...",4.2,https://im1.dineout.co.in/images/uploads/resta...
9,Indian Grill Room,"Suncity Business Tower,Golf Course Road, Gurgaon","North Indian, Mughlai",4.3,https://im1.dineout.co.in/images/uploads/resta...
10,Mad 4 Bar B Que,"Sector 29, Faridabad",North Indian,3.6,https://im1.dineout.co.in/images/uploads/resta...
11,Barbeque 29,"NIT, Faridabad","North Indian, Mughlai, Desserts, Beverages2 d...",4.2,https://im1.dineout.co.in/images/uploads/resta...
12,Glasshouse,"DoubleTree By Hilton Gurugram Baani Square,Sec...","European, Italian, Asian, Continental1 offer ...",4,https://im1.dineout.co.in/images/uploads/resta...